version: '3.9'
services:
  models-bee-detector:
    build:
      context: .
      dockerfile: Dockerfile.prod
#    command:
#      python3 /app/server.py
    environment:
      - ENV_ID=prod
    ports:
      - 8700:8700
      - 8126:8126
    volumes:
      - .:/app/
    restart: always
    network_mode: host
