version: '3.8'
services:
  models-bee-detector:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command:
      ddtrace-run python3 /app/server.py
    environment:
      - ENV_ID=prod
      - DD_SERVICE=models-bee-detector
      - DD_ENV=prod
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
    ports:
      - 8700:8700
    volumes:
      - .:/app/
    restart: always
    network_mode: host
